# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Codigo para manejar ambientes y el codigo necesario
COPY environment_pandas.yml .
COPY app.py .

ENV PATH /opt/conda/bin:$PATH

RUN conda env create -f environment_pandas.yml
RUN conda activate environment_pandas




# Define el comando por defecto para ejecutar la aplicación
CMD ["python", "app.py"]